### PR TITLE
Minor suggestion

### PR DESCRIPTION
**Pull request by arichar6**
I wanted to play around with the new code. I ended up making some minor changes. Also, I moved the tests into their own file. But I don't know what the "best practice" is on organizing tests. Should these be in their own file? Or should they go back into the "core" tests?

### CODE REVIEW

**Comment by arichar6** [comment]
Do you know what the best organization for tests should be?

**Comment by gracetangg** [comment]
@arichar6 Sorry I didn't realize we could do this on git! Maybe we can make a test file for all new features in different releases? Or we could make a different test file for all of the classes in core (their subclasses included in the same file).

**Comment by arichar6** [comment]
Those both sound like reasonable solutions. Do you mind doing a bit of research to see what the standard/best practices are for python packages that use pytest? Maybe check to see what numpy does, or plasmapy?

Thanks!

**Comment by gracetangg** [comment]
[This article](https://medium.com/worldsensing-techblog/tips-and-tricks-for-unit-tests-b35af5ba79b1#:~:text=Organize%20your%20test%20by%20concern&text=Pytest%20can%20help%20you%20in,%3A%20folders%2C%20markers%2C%20names%20%E2%80%A6&text=If%20smoke%20tests%20are%20not,mark.) suggests splitting into suites that test for configuration/initialization, unit tests, and integration tests. [plasmapy](https://github.com/PlasmaPy/PlasmaPy/tree/master/plasmapy/formulary) and [numpy](https://github.com/numpy/numpy/tree/master/numpy/core) have a different test file for each module, like we have right now, but neither of them have different classes in one file.

**Comment by arichar6** [comment]
That is a pretty helpful article. I that that, since our `core.py` has quite a lot in it, it's ok to split up the tests. I may also split up the source files, too, eventually.

**Pull request merged**
